title = "MQTT Observing Conditions"

[network]
ip_address = ''             # Any address
port = 5555

[server]
location = 'Maurertown, Virginia, USA'  # Anything you want here
verbose_driver_exceptions = true

[device]
mqtt_port = 1883
topic_cloud_cover = 'weather/cloudCover'
topic_dew_point = 'weather/dewptc'
topic_event_rain = 'weather/eventrainmm'
topic_humidity = 'weather/humidity'
topic_pressure = 'weather/baromrelhpa'
topic_solar_radiation = 'weather/solarradiation'
topic_sqm = 'sqm'
topic_temperature = 'weather/tempc'
topic_wind_direction = 'weather/winddir'
topic_wind_gust = 'weather/windgustkmh'
topic_wind_speed = 'weather/windspeedkmh'

[logging]
log_level = 'INFO'
log_to_stdout = true
max_size_mb = 5
num_keep_logs = 10
