title = "MQTT Observing Conditions"

[network]
ip_address = ''             # Any address
port = 5555

[server]
location = 'Maurertown, Virginia, USA'  # Anything you want here
verbose_driver_exceptions = true

[logging]
log_level = 'INFO'
log_to_stdout = true
max_size_mb = 5
num_keep_logs = 10
